llm:
  # model_id: "microsoft/Phi-4-mini-instruct" V1-phi4
  model_id: "Qwen/Qwen3-4B-Instruct-2507"
  max_new_tokens: 1024
  temperature: 0.3

plagiarism_detection:
  sample_size: 1500        
  split:
    test_size: 0.2
    random_state: 42
  model: logistic_regression   